### ISSUE TITLE
W3C Validation Error

### ISSUE THREAD

**Issue by Macxim** [am-impact/amforms#65] opened 2016-04-12 15:06 UTC
Hey!

Very nice work with the plugin. Thanks.

When validating a page with a form, I get 
`Element style not allowed as child of element form in this context.`

Code sample:

```html
<form method="post" action="" class="form contact-form" accept-charset="UTF-8">
  <input type="hidden" name="action" value="amForms/submissions/saveSubmission">
  <input type="hidden" name="handle" value="contactForm">
  
  <div class="yourssince1615__wrapper">
    <label>Leave this field blank</label>
    <input type="text" id="yourssince1615" name="yourssince1615" value="">
  </div>
  <style>.yourssince1615__wrapper{ display: none; }</style>

  <input type="hidden" id="__UATIME" name="__UATIME" value="1460473164" />
  <input type="hidden" id="__UAHOME" name="__UAHOME" value="043a1251a7f624ae3e2e4a0a30676fec" />
  <input type="hidden" id="__UAHASH" name="__UAHASH" value="87053d2675cf68a0f94a335ed8c0f900"/>
  ....
</form>
```

**Comment by onebrightlight** [comment] 2016-04-12 16:33
Your `style` element can't live inside a `form` element, I believe. The issue is in your markup, but not the plugin. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style

**Comment by Macxim** [comment] 2016-04-12 18:03
Yes, I know.
The sample that I pasted above is the generated code.
In my template I have it this way.
```html
<form method="post" action="#" class="form contact-form" accept-charset="UTF-8">
  {{ getCsrfInput() }}

  {# This should always be here! #}
  <input type="hidden" name="action" value="amForms/submissions/saveSubmission">

  {# Insert your form's handle. #}
  <input type="hidden" name="handle" value="contactForm">

  {# Optional: Anti-spam protection. #}
  {{ craft.amForms.displayAntispam() }}
  .....
</form>
```
I doubt that I can move `{{ craft.amForms.displayAntispam() }}` outside of the form, can I?

**Comment by onebrightlight** [comment] 2016-04-12 23:06
You can't move it out of the form, but you can manually create the contact form. I find it's much better to have that level of control of the output anyway.

You have a valid point though, if this is part of the form tag, hopefully they'll get a chance to modify this as needed.

**Comment by hubertprein** [comment] 2016-04-14 09:28
We've noticed this in our checks as well. Trying to come up with a decent solution so your anti spam still works flawless.

**Comment by onebrightlight** [comment] 2016-04-14 22:18
Wouldn't either inlining the CSS or placing the `style` element before the `form` tag work as well?

**Comment by hubertprein** [comment] 2016-04-25 13:29
Fixed in latest release.

**Comment by Macxim** [comment] 2016-04-25 13:29
Thanks @hubertprein :+1:

**Closed by hubertprein** 2016-04-25 13:29 UTC
